modLoader = "javafml"
loaderVersion = "[21,)"
license = "MIT"

[[mods]]
modId = "cobblemon_neoforge_mdk"
version = "1.0.0"
displayName = "Cobblemon NeoForge Template Sidemod"
description = '''

'''

[[dependencies.cobblemon_forge_mdk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_forge_mdk]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_forge_mdk]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "NONE"
side = "BOTH"
