modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"

[[mods]]
modId = "cobblemon_forge_mdk"
version = "1.0.0"
displayName = "Cobblemon Forge Template Sidemod"
description = '''

'''

[[dependencies.cobblemon_forge_mdk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_forge_mdk]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.cobblemon_forge_mdk]]
#modId = "cobblemon"
#mandatory = true
#versionRange = "[1.2.0,2.0)"
#ordering = "NONE"
#side = "BOTH"
